name: "Checkout Repo"

description: "Action to checkout GIT Repository with special reference handling."

branding:
  icon: "download"
  color: "green"

inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
    required: false
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
    required: false
    default: ${{ github.ref }}
  alt_ref:
    description: >
      The alternative branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that event. Otherwise, uses the default branch.
    required: false
  order:
    description: >
      Direction of sort in case of a regular expression for your reference. ('top' or 'down')
      Example: In case if ref=v* with tags v1, v2, v3 you will get v3 as a valid reference
    required: false
    default: 'top'
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
    default: ''
  lfs:
    description: 'Whether to download Git-LFS files'
    required: false
    default: 'false'
  submodules:
    description: >
      Whether to checkout submodules: `true` to checkout submodules or `recursive` to
      recursively checkout submodules.
    required: false
    default: 'false'
  include:
    description: >
      Explicitly include files for LFS
    required: false
    default: '*'
  exclude:
    description: >
      Explicitly exclude files for LFS
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # Show debug information
    - name: Show debug information
      run: |
          echo "github repo: ${{ github.repository }}"
          echo "input repo: ${{ inputs.repository }}"
      shell: bash

    # Call normal checkout action: see https://github.com/actions/checkout
    # use default branch
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository:  ${{ inputs.repository }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        lfs: ${{ inputs.lfs }}   
        submodules:  ${{ inputs.submodules }}   
        fetch-depth: 0
   
    # Call normal checkout action: see https://github.com/actions/checkout
    # this is neccessary for own ci test
    - name: Checkout own action code
      if: ${{ github.repository == 'rohmanngmbh/action-checkout-repo' }}
      uses: actions/checkout@v3
      with:
        repository: rohmanngmbh/action-checkout-repo
        ref: ${{ github.ref }}
        path: .temp

    # Call normal checkout action: see https://github.com/actions/checkout
    - name: Checkout own action code
      if: ${{ github.repository != 'rohmanngmbh/action-checkout-repo' }}
      uses: actions/checkout@v3
      with:
        repository: rohmanngmbh/action-checkout-repo
        ref: v1.3.1       # <<<<< release tag or main
        path: .temp

    # Run python (environment variables has to be set separately https://github.com/actions/runner/issues/665)
    - name: Run handle reference on linux/mac
      if: ${{ runner.os != 'Windows' }}
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REPOSITORY:  ${{ inputs.repository }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_ALT_REF: ${{ inputs.alt_ref }}
        INPUT_ORDER: ${{ inputs.order }}
      shell: bash
      run: |
        cd .temp
        pip3 install virtualenv
        python3 -m venv ~/venvs/venv3
        source ~/venvs/venv3/bin/activate
        echo "*************** Post-Run Checkout ***************"
        pip3 install -r requirements.txt
        python3 main.py
        deactivate
        python3 -m venv ~/venvs/venv3 --clear
        rm -rf ~/venvs/venv3
        cd ..
        echo "*************** Change Reference "***************

    # Run python (environment variables has to be set separately https://github.com/actions/runner/issues/665)
    - name: Run handle reference on windows
      if: ${{ runner.os == 'Windows' }}
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_REPOSITORY:  ${{ inputs.repository }}
        INPUT_REF: ${{ inputs.ref }}
        INPUT_ALT_REF:  ${{ inputs.alt_ref }}
        INPUT_ORDER: ${{ inputs.order }}
      shell: cmd
      run: |
        echo "*************** Post-Run Checkout ***************"
        cd .temp
        pip install -r requirements.txt
        python main.py
        cd ..
        echo "*************** Change Reference "***************
  
    # Show ref information
    - name: Show ref information
      run: |
          echo "my_ref: ${{ env.my_ref }}"
      shell: bash

    # Switch reference of cloned repo
    - name: Switch reference of cloned repo
      if: ${{ inputs.path == '' }}
      run: |
        git fetch
        git checkout ${{ env.my_ref}}
      shell: bash

    # Switch reference of cloned repo
    - name: Switch reference of cloned repo
      if: ${{ inputs.path != '' }}
      run: |
        cd ${{ inputs.path }}
        git checkout ${{ env.my_ref}}
      shell: bash

    # Handle git lfs stuff: see https://github.com/nschloe/action-cached-lfs-checkout
    # in case of base path
    - name: Create LFS file list
      if: ${{ inputs.lfs == 'true' &&  inputs.path == '' }}
      run: |
        git lfs ls-files --long --include  "${{ inputs.include }}" --exclude  "${{ inputs.exclude }}" | cut -d ' ' -f1 | sort > .lfs-assets-id
      shell: bash

    - name: Restore LFS cache
      if: ${{ inputs.lfs == 'true' &&  inputs.path == '' }}
      uses: actions/cache@v3
      id: lfs-cache-base
      with:
        path: .git/lfs
        key: lfs-${{ hashFiles('.lfs-assets-id') }}-v1

    - name: Git LFS Pull
      if: ${{ inputs.lfs == 'true' &&  inputs.path == '' }}
      run: git lfs pull --include  "${{ inputs.include }}" --exclude  "${{ inputs.exclude }}"
      shell: bash

    # in case of special path
    - name: Create LFS file list
      if: ${{ inputs.lfs == 'true' &&  inputs.path != '' }}
      run: |
        cd ${{ inputs.path }}
        git lfs ls-files --long --include  "${{ inputs.include }}" --exclude  "${{ inputs.exclude }}" | cut -d ' ' -f1 | sort > .lfs-assets-id
      shell: bash

    - name: Restore LFS cache
      if: ${{ inputs.lfs == 'true' &&  inputs.path != '' }}
      uses: actions/cache@v3
      id: lfs-cache-special
      with:
        path: ${{ inputs.path }}/.git/lfs
        key: lfs-${{ hashFiles('.lfs-assets-id') }}-v1

    - name: Git LFS Pull
      if: ${{ inputs.lfs == 'true' &&  inputs.path != ''}}
      run: |
        cd ${{ inputs.path }}
        git lfs pull --include  "${{ inputs.include }}" --exclude  "${{ inputs.exclude }}"
      shell: bash
