#######################################################
# This is the main CI workflow test
#######################################################
name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test local action
  Test-Local-Action:
    # The type of runner that the job will run on: ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, windows-latest, windows-2019, macos-12, macos-11, macos-10.15 ]
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checksout action repository under $GITHUB_WORKSPACE
      - name: Checkout action repository
        uses: actions/checkout@v3
        with:
          ref: develop

      # Run checkout this repository to path 'myself'
      - name: Checkout this repository
        id: myself-ref
        uses: ./
        with:
          path: myself-ref
          ref: ${{ github.ref }}

      - name: Test myself-ref
        run: |
          test "${{ steps.myself-ref.outputs.ref == github.ref }}"
        
      # Run checkout an extern example repository to 'extern'
      - name: Checkout an extern repository
        id: extern
        uses: ./
        with:
          repository: githubtraining/community-contributors
          path: extern
          ref: main

      - name: Test extern
        run: |
          test "${{ steps.extern.outputs.ref == 'main' }}"

      # Run checkout an git lfs example repository to folder 'git-lfs'
      - name: Checkout a git-lfs repository
        id: git-lfs
        uses: ./
        with:
          repository: Apress/repo-with-large-file-storage
          path: git-lfs
          ref: master
          lfs: true

      - name: Test git-lfs
        run: |
          test "${{ steps.git-lfs.outputs.ref == 'master' }}"

      # Run checkout this repository to path 'default' to choose default branch
      - name: Checkout this repository at default reference
        uses: ./
        with:
          path: myself-default

      # Run checkout this repository to path 'alt-ref-default' to choose default branch
      - name: Checkout this repository at alternative reference
        uses: ./
        with:
          path: myself-alt-ref-default
          ref: not/existing/feature/branch
        
      # Run checkout this repository to path 'alt-ref-branch' to choose an explicit alternative branch
      - name: Checkout this repository at alternative reference (branch)
        id: alt-ref-branc
        uses: ./
        with:
          path: myself-alt-ref-branch
          ref: not/existing/feature/branch
          alt_ref: develop

      - name: Test alt-ref-branch
        run: |
          test "${{ steps.alt-ref-branch.outputs.ref == 'develop' }}"

      # Run checkout this repository to path 'alt-ref-tag' to choose an explicit alternative tag
      - name: Checkout this repository at alternative reference (tag)
        id: alt-ref-tag
        uses: ./
        with:
          path: myself-alt-ref-tag
          ref: not/existing/feature/branch
          alt_ref: v0.1

      - name: Test alt-ref-tag
        run: |
          test "${{ steps.alt-ref-tag.outputs.ref == 'v0.1' }}"

      # List folder recursive (only for debugging)
      - name: List folders
        run: |
          ls -R
    
  # Test marketplace action
  Test-Marketplace-Action:
    # The type of runner that the job will run on: ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, windows-latest, windows-2019, macos-12, macos-11, macos-10.15 ]
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Run checkout this repository with own action (last deployed)
      - name: Checkout this repository with own action (last deployed)
        uses: rohmanngmbh/action-checkout-repo@v1.1.0
        with:
          path: myself-release-ref
          ref: ${{ github.ref }}

      # Run checkout this repository with own action (last main)
      - name: Checkout this repository with own action (last main)
        uses: rohmanngmbh/action-checkout-repo@develop
        with:
          path: myself-main-ref    
          ref: ${{ github.ref }}
        
      # Run checkout an extern example repository to 'extern'
      - name: Checkout an extern repository
        uses: rohmanngmbh/action-checkout-repo@develop
        with:
          repository: githubtraining/community-contributors
          path: extern
          ref: main

      # Run checkout an git lfs example repository to folder 'git-lfs'
      - name: Checkout a git-lfs repository
        uses: rohmanngmbh/action-checkout-repo@develop
        with:
          repository: Apress/repo-with-large-file-storage
          path: git-lfs
          ref: master
          lfs: true

      # Run checkout this repository to path 'default' to choose default branch
      - name: Checkout this repository at default reference
        uses: rohmanngmbh/action-checkout-repo@develop
        with:
          path: myself-default

      # Run checkout this repository to path 'alt-ref-default' to choose default branch
      - name: Checkout this repository at alternative reference
        uses: rohmanngmbh/action-checkout-repo@develop
        with:
          path: myself-alt-ref-default
          ref: not/existing/feature/branch
        
      # Run checkout this repository to path 'alt-ref-branch' to choose an explicit alternative branch
      - name: Checkout this repository at alternative reference (branch)
        uses: rohmanngmbh/action-checkout-repo@develop
        with:
          path: myself-alt-ref-branch
          ref: not/existing/feature/branch
          alt_ref: develop

      # Run checkout this repository to path 'alt-ref-tag' to choose an explicit alternative tag
      - name: Checkout this repository at alternative reference (tag)
        uses: rohmanngmbh/action-checkout-repo@develop
        with:
          path: myself-alt-ref-tag
          ref: not/existing/feature/branch
          alt_ref: v0.1

      # List folder recursive (only for debugging)
      - name: List folders
        run: |
          ls -R
